name: Unit Test

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends make gcc g++ cmake libgtest-dev

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run Unit Test
        run: cmake --build build -- -j$(nproc) test_run
